### PR TITLE
Bug fix/wassim/error emptyrecipes list

### PR DESCRIPTION
**Pull request by khedirwassim**

### CODE REVIEW

**Comment by eisenhowair** [comment]
checking changes

**Comment by eisenhowair** [comment]
image

**Comment by khedirwassim** [comment]
it works for me are you sure you don't have any problems with links or paths
Capture d’écran 2024-02-10 204644

**Comment by khedirwassim** [comment]
it works for me are you sure you don't have any problems with links or paths
Capture d’écran 2024-02-10 204759

**Comment by khedirwassim** [comment]
it works for me are you sure you don't have any problems with links or paths
Capture d’écran 2024-02-10 205022

**Comment by eisenhowair** [comment]
> it works for me are you sure you don't have any problems with links or paths Capture d’écran 2024-02-10 205022

Tu pourrais montrer les valeurs que tu as mises dans le formulaire?

**Comment by khedirwassim** [comment]
ah i know the problem. i updated the sql file you need to make the id in recipes table  auto increment

**Comment by khedirwassim** [comment]
Capture d’écran 2024-02-10 205444

**Comment by khedirwassim** [comment]
Capture d’écran 2024-02-10 205502

**Comment by khedirwassim** [comment]
Capture d’écran 2024-02-10 205517

**Pull request merged**
